In [4]:
import sys, os
sys.path.append(os.path.abspath('..'))
from src.ml import run_all_models
from src.get_data import get_data_processed

In [6]:
df = get_data_processed('methods_1.csv')
df.tail()

Đã đọc thành công dữ liệu từ: C:\Users\YOGA\Desktop\MyProjects\datathon\github\vimchanhxa-datathon\data\processed\methods_1.csv

,date,revenue,cogs,is_test,day_of_week,day_of_month,day_of_year,month,year,is_weekend,is_payday,is_double_day,days_since_start,days_to_tet,is_pre_tet_rush,is_tet_holiday,is_promo,total_discount
4376,2024-06-27,NaN,NaN,1,3,27,179,6,2024,0,1,0,4376,-138,0,0,0,0.0
4377,2024-06-28,NaN,NaN,1,4,28,180,6,2024,0,1,0,4377,-139,0,0,0,0.0
4378,2024-06-29,NaN,NaN,1,5,29,181,6,2024,1,1,0,4378,-140,0,0,0,0.0
4379,2024-06-30,NaN,NaN,1,6,30,182,6,2024,1,1,0,4379,-141,0,0,0,0.0
4380,2024-07-01,NaN,NaN,1,0,1,183,7,2024,0,1,0,4380,-142,0,0,0,0.0

In [10]:
df = df[df['is_test'] == 0].copy()  # Chỉ sử dụng dữ liệu train để đánh giá mô hình

target = 'revenue'
features = [col for col in df.columns if col not in ['date','is_test', 'cogs', target]]

results = run_all_models(df, target_col=target, feature_cols=features)
results

Done: LinearRegression
Done: Ridge
Done: Lasso
Done: ElasticNet
Done: BayesianRidge
Done: HuberRegressor
Done: DecisionTree
Done: RandomForest
Done: ExtraTrees
Done: HistGradientBoosting
Done: AdaBoost
Done: LightGBM
Done: LightGBM_DART
Done: XGBoost
Done: CatBoost

                   Model           MAE          RMSE       MAPE  R-squared
0               CatBoost  5.421894e+05  7.625633e+05  18.009269   0.792442
1                XGBoost  5.616388e+05  7.677606e+05  19.561567   0.789603
2               LightGBM  5.904414e+05  8.095604e+05  20.028097   0.766070
3   HistGradientBoosting  6.025878e+05  8.213319e+05  20.220865   0.759217
4           RandomForest  6.365988e+05  8.899411e+05  21.149634   0.717310
5             ExtraTrees  6.583281e+05  9.089894e+05  22.235339   0.705079
6          LightGBM_DART  7.187371e+05  9.748992e+05  22.233282   0.660760
7           DecisionTree  7.897867e+05  1.111711e+06  26.125781   0.558865
8          BayesianRidge  8.916997e+05  1.237642e+06  36.216165   0.453264
9       LinearRegression  8.982507e+05  1.243098e+06  35.277134   0.448433
10                 Ridge  9.007006e+05  1.245527e+06  36.201578   0.446275
11                 Lasso  9.788009e+05  1.317791e+06  38.290376   0.380158
12        HuberRegressor  1.081544e+06  1.484343e+06  37.134695   0.213576
13            ElasticNet  1.070053e+06  1.493153e+06  39.659441   0.204214
14              AdaBoost  1.361276e+06  1.633617e+06  62.958059   0.047449